[build]
  command = "cd frontend && yarn install && DISABLE_ESLINT_PLUGIN=true yarn build"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "1.22.19"
  DISABLE_ESLINT_PLUGIN = "true"

# Configuración para Functions (Workers)
[functions]
  directory = "functions"

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; script-src 'self'; connect-src 'self' https:"

# Redirects para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Country = ["*"]}
  headers = {cache-control = "max-age=0"}

# Cache estático
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"